name: tigramnks
description: A new Flutter application.

publish_to: 'none' 

version: 1.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_typeahead: ^5.2.0
  flutter_native_splash: ^2.3.10
  toggle_switch: ^2.1.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  mobile_scanner: ^6.0.7
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_datagrid: ^23.2.7
  hexcolor: ^3.0.1
  schedulers: ^0.3.1
  get: ^4.6.6
  new_gradient_app_bar: ^0.2.0  # Downgraded version
  fading_edge_scrollview: ^4.0.0
  fl_chart: ^0.70.2
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  file_picker: ^9.0.2
  flutter_staggered_grid_view: ^0.7.0
  pdf: ^3.10.4
  jailbreak_root_detection: ^1.1.5
  flutter_keyboard_visibility: ^6.0.0
  lottie: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # syncfusion_flutter_charts: ^24.1.44
  flutter_launcher_icons: ^0.13.1
  launcher_name: ^1.0.2
  sqflite: ^2.3.0
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  http: ^1.3.0
  pie_chart: ^5.4.0
  dio: ^5.4.0
  flutter_downloader: ^1.11.6
  provider: ^6.1.2
  expansion_tile_card: ^3.0.0
  marquee: ^2.2.3
  flutter_lints: ^3.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.jpg"

flutter_launcher_name:
  name: "Tigram"

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png 
    - assets/images/apply_icon.png
    - assets/images/check_status.png
    - assets/images/question_icon.png
    - assets/images/kerala_logo.jpg
    - assets/images/ministry_logo.jpg
    - assets/images/usaid_logo.png
    - assets/images/tigram01.png
    - assets/tree.json
